language: c++
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
env:
  - BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Debug
  - BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Debug
  - BUILD_SHARED_LIBS=OFF CMAKE_BUILD_TYPE=Release
  - BUILD_SHARED_LIBS=ON  CMAKE_BUILD_TYPE=Release
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y \
      && sudo apt-get update -qq \
      && if [ "$CXX" == "g++" ]; then
        sudo apt-get install -qq g++-4.7 && export CXX="g++-4.7" CC="gcc-4.7"
      fi
    fi
before_script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
script:
  - make
  - test/run-tests
