environment:
  PROJECT_FOLDER: "c:/projects/yaml-cpp"
  INSTALL_PREFIX: "c:/installs"

# branches to build
branches:
  # whitelist
  only:
    - add-appveyor-tests

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:


# clone directory
clone_folder: %PROJECT_FOLDER%

platform: x64
configuration: Release

install:

# scripts to run before build
before_build:
  - cd %PROJECT_FOLDER%
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=%INSTALL_PREFIX%

# What solutions to build
build:
  project: ALL_BUILD.vcxproj

# scripts to run after build
after_build:
  - cd test/Release
  - run-tests.exe

